name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install uv
      run: pip install uv

    - name: Setup dependencies
      run: |
        uv venv create env
        source env/bin/activate
        uv pip install -r requirements.txt
        uv pip install pytest

    - name: Run linting
      run: |
        source env/bin/activate
        uv pip install pre-commit
        pre-commit run --all-files

    - name: Run tests
      run: |
        source env/bin/activate
        pytest